version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: mbtourplanner_db
    environment:
      POSTGRES_USER: touradmin
      POSTGRES_PASSWORD: tourpass
      POSTGRES_DB: mbtourplanner
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: tourplanner_adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  pgdata: